### ISSUE TITLE
Raise cryptography.exceptions.InvalidTag

### ISSUE THREAD

**Issue by wattswing** [wodny/decrypt-2fas-backup#1]
Greetings,

Thanks for your work on this script.
I'm trying to decrypt an exported file from Google Authenticator app.

Requirements:
```
% uname -a
Linux wattpad 6.0.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 03 Nov 2022 18:01:58 +0000 x86_64 GNU/Linux

% python -V
Python 3.10.8

% pip3 install cryptography
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: cryptography in /usr/lib/python3.10/site-packages (38.0.3)
Requirement already satisfied: cffi>=1.12 in /usr/lib/python3.10/site-packages (from cryptography) (1.15.1)
Requirement already satisfied: pycparser in /usr/lib/python3.10/site-packages (from cffi>=1.12->cryptography) (2.21)
```

Executing the script:
```
% ./decrypt-2fas-backup.py mypass ~/Downloads/2fas-backup-20221107223516.2fas
Traceback (most recent call last):
  File "/home/userspace/workspace/crypto/decrypt-2fas-backup/./decrypt-2fas-backup.py", line 51, in <module>
    main()
  File "/home/userspace/workspace/crypto/decrypt-2fas-backup/./decrypt-2fas-backup.py", line 46, in main
    credentials_dec = aesgcm.decrypt(nonce, credentials_enc, None)
  File "/usr/lib/python3.10/site-packages/cryptography/hazmat/primitives/ciphers/aead.py", line 210, in decrypt
    return aead._decrypt(backend, self, nonce, data, [associated_data], 16)
  File "/usr/lib/python3.10/site-packages/cryptography/hazmat/backends/openssl/aead.py", line 249, in _decrypt
    raise InvalidTag
cryptography.exceptions.InvalidTag
```

Would you have any clue?
Thanks.

Kindly,
W

**Comment by wodny** [comment]
Hi, sorry for a late response. I've missed the notification. The script is for use with the 2FAS application, not the Google Authenticator. BTW, I cannot find an export option in the Google Authenticator, just a way to share a secret using a QR code. Did the app create a file with the `.2fas` extension?

**Comment by wattswing** [comment]
Hi, thanks for getting back to me.

Sorry my former statement was an error:
> I'm trying to decrypt an exported file from Google Authenticator app.

It's indeed an export from "2FAS Auth" app on Android.

**Comment by wodny** [comment]
I was able to get the exact same exception when I used a wrong password. Maybe there are some special characters interpreted by shell (like exclamation mark)? You can try quoting the password or putting it into a file, eg. `pass` and then running:
```sh
$ ./decrypt-2fas-backup.py @pass ~/2fas-backup-20230130122617.2fas
```
