### ISSUE TITLE
Add default_backend to PBKDF2HMAC

### ISSUE THREAD

**Issue by RobertJHowell** [wodny/decrypt-2fas-backup#2]
Hi Wodny, thanks for the great script. It's simple and easy to understand.
The call to PBKDF2HMAC needs an extra argument before the closing paren backend=default_backend()
so the script needs this extra import
from cryptography.hazmat.backends import default_backend

Thanks again for your great code
Best wishes
Rob Howell

**Comment by wodny** [comment]
Hi, the `backend` argument is deprecated. See: https://github.com/pyca/cryptography/issues/6499
